### ISSUE TITLE
Filtered Applications

### ISSUE THREAD

**Issue by toadlyBroodle** [TechnikEmpire/StahpIt-WPF#5]
When checkbox selected beside filtered application on dashboard screen, StahpIt blocks all http/https traffic from that app. Not sure if this is the intended behavior? I assume that filtering an application is supposed to only block addresses on the blocklists, is this right?

**Comment by TechnikEmpire** [comment]
Which app? Is it a standard browser? As the notes say under the box, there are some apps that might be using those ports, but are not actually speaking HTTP. In this case, in its present condition, the Engine will silently fail via timeout, because it's doing an async read waiting for a HTTP header terminating CRLF.

**Comment by TechnikEmpire** [comment]
However, I've noticed that sometimes the WinDivert driver fails to start inexplicably. Not sure if that's my fault or something in WinDivert yet. If its a browser you're trying to filter, try completely exiting the app and restarting it. Worst case scenario, you can fully exit and then open an elevated command prompt and type:

```
sc stop WinDivert1.2
```

This will force the driver to be completely shut down. The next time you run the app, it should reload the driver. If this error goes away after forcing WinDivert to unload, then this is indeed the problem.

**Comment by TechnikEmpire** [comment]
Oh, also note that some AV software with a firewall component can clash with Stahp It. So far the only confirmed issue is with BitDefender's firewall. It gets into a full fledged brawl with Stahp It's packet diversion and locks it up. Kaspersky works fine, and one thing to note is that whatever firewall solution you have, you'll probably have to disable SSL scanning within the firewall otherwise it's going to cry about Stahp It's signed certificates.

Also you're correct in your understanding of the intended function. Apps that get checked for filtering simply means that their HTTP and HTTPS traffic is run through a process that is nearly identical to having Adblock Plus installed in that program. All loaded ABP rules will be processed against requests from those apps, and ad elements removed from HTML that is served to those checked off apps.

Methinks I'm going to change the release from "Release Candidate 1" to "Beta 1", haha.

**Comment by clankwright** [comment]
Ok right on, thanks for the quick reply. Yes it was blocking all traffic from Firefox when I selected it. It's not an issue with my antivirus. I'll try rebooting and the other things you suggested and see if that helps. Thanks. 

Can I ask how many other people have reviewed the source for the underlying GQ and HttpFilteringEngine projects?

**Comment by TechnikEmpire** [comment]
Oh thats odd, did another browser work while Firefox didn't? Let me know, because that's definitely an issue I'd want to get to the bottom of.

As far as the source code for the underlying C++ components, nobody has reviewed or commented on anything, except maybe one guy (it's a guy who also follows the @Divert project like I do, we've discussed things briefly which basically makes us best friends (jokes)).

People don't seem to really care, which I can't understand because AFAIK, not tooting my own horn, GQ is the fastest CSS selector engine there is. GQ is a bottom up rewrite of the Gumbo-Query project, which is horribly broken. I tried sharing info about the 100s of bugs I fixed but, people ignored me and they keep using the original project. I don't want to actively try and steal those users away or anything. So yeah, basically nobody. Can I ask why you ask?

**Comment by clankwright** [comment]
Oh I just haven't looked through your source thoroughly yet, so was hoping others have already. Anywho, you're Canadian too so I totally trust you ;) But yeah that's interesting that there's not more interest in it. I've been looking for such an app ever since MS took the liberty of infusing my windows experience with ads. If I can get it working, I'd be interested in learning more about it and helping out where I can, though I'm not that skilled yet.

**Comment by TechnikEmpire** [comment]
haha yes I'm Canadian, in fact I've been itching to apologize for something so I formally apologize for your bad experience so far. Yeah I definitely get the security concern, it is intercepting your web traffic after all. If its any comfort, I publish my real name in my copyright notice. Uploading to Github means I've exported to the United States, which means that if I did anything illegal here, I'd be spending the next decade or more of my life being passed around internationally to various prisons, and I'm not really fond of that idea. :smile: 

Once you have it working, you can start enabling Stahp It on processes like explorer.exe and it should start blocking stuff, including ads that they show in the news app and such. I appreciate you wanting to help out and don't worry about what you're skilled at, this kind of feedback alone is immensely helpful.

**Comment by clankwright** [comment]
I'm Canadian too, so we're also basically best friends:) also I'm sorry for finding a bug so soon after install! 

So far it's completely blocking all traffic from any app I enable filtering for including browsers, i.e. Firefox, MicrosoftEdge. I killed the app a few times, still not working. Then killed WinDivert, still not working...

Not sure what the problem is, when I have time I'll dl the source and see if I can get some logs with more info on what's going on.

**Comment by clankwright** [comment]
I'm running Win10 btw, if it helps. Let me know if you have any other troubleshooting suggestions. I'll keep an eye on future activity here also. Cheers.

**Comment by TechnikEmpire** [comment]
lol!, well that sucks. As far as the source, I still have to write out all the build instructions for the dependencies (they're half done, unfortunately the HttpFilteringEngine project is insane for build process). I think I'll tackle that first so that you can do a full standalone build and then I'll investigate further. The app writes errors to a log file in `APP_INSTALL_DIR\logs`. Go ahead and review that, and if you are comfortable with posting that log here, that would be a big help. Sometimes it can dump domains being resolved depending the set log level, so if that's the case just look for error codes and stack traces, paste in that stuff.

**Comment by clankwright** [comment]
Found one of these in the log:
   **could not find certificate named "Stahp It CA": SEC_ERROR_BAD_DATABASE: security library: bad database.**
a few of these:
    **ERROR In WinDiverter::GetPacketProcess(const unsigned long) - Failed to get binary path.**
a couple of these:
   **ERROR FF Cleanup Error: Notice: Trust flag u is set automatically if the private key is present.**
and alot of these:
   **ERROR In HttpFilteringEngine::ProcessAbpFormattedRule(const std::string&, const uint8_t) - Got error: In AbpFilterParser::ParseFilterPart(boost::string_ref&, const boost::string_ref::size_type) const - Failed to parse anything. Empty string or out of bounds.**
     - which I assume is just an issue with parsing certain members of easylist?

Hope this helps, happy coding :)

**Comment by TechnikEmpire** [comment]
So the firefox bad DB error is that the cert didn't exist already in Firefox when it tried to remove the old CA cert, that's normal. The trust flag thing is normal output as well for when the cert is installed to firefox. The ProcessAbpFormattedRule error is just that a certain rule was not parsed correctly. It prints the error but it should handle it. What URL did you feed to Stahp It for easylist? Was it:

```
https://easylist-downloads.adblockplus.org/easylist.txt
```

I'm curious now if maybe the list has loaded in a screwed up way where the parser has, via a bug, created a rule that ends up blocking everything haha. I've never seen that before if that is the case, but its my only running theory.

You can edit Nlog.config manually in the app folder and change the log level to "Debug" and it will print A LOT more stuff. 

```
<rules>
     <!-- add your logging rules here -->    
-    <logger name="*" minlevel="Error" writeTo="StahpIt" />     (change this to...)
+   <logger name="*" minlevel="Debug" writeTo="StahpIt" />   (... this)

   </rules>
```

**Comment by clankwright** [comment]
Yes I gave it that easylist URL. I'll try debugging it when I have time :)
